
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/home/gradle
    ports:
      - 8080:8080

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
    restart: always
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  db:
    container_name: database
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: app
      encoding: utf8
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U postgres_user -d app
      interval: 2s
      timeout: 3s
      retries: 40
    ports:
      - 5432:5432

volumes:
  node_modules:
  next_build:
  db_data: